name = "triage-by-trivial-security"
main = "src/main.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "d1db"
database_name = "trivial_triage"
database_id = "6420dc05-dcaf-43cc-b6f7-03139d6b5988"
