name: npm-artifacts
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: |
          npm run build
          npm sbom --omit dev --package-lock-only --sbom-format cyclonedx | jq >npm.cdx.json

      - name: Upload semgrep.sarif.json
        uses: actions/upload-artifact@v4
        with:
          name: semgrep_sarif
          path: semgrep.sarif.json

      - name: Upload npm.cdx.json
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: npm.cdx.json

      - name: Generate SBOM attestation
        uses: actions/attest-sbom@v1
        with:
          subject-path: ""
          sbom-path: npm.cdx.json

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
